// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhy1W_Nwk_5p_MdQTraUss5rNanD54Tds',
    appId: '1:964464805510:web:eba3c3ad9142f880447307',
    messagingSenderId: '964464805510',
    projectId: 'messaging-app-371aa',
    authDomain: 'messaging-app-371aa.firebaseapp.com',
    storageBucket: 'messaging-app-371aa.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfMQa879CBWiQFofE2JexwUd-Kt23I-dY',
    appId: '1:964464805510:android:35e94267f915f2bf447307',
    messagingSenderId: '964464805510',
    projectId: 'messaging-app-371aa',
    storageBucket: 'messaging-app-371aa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiS8bt7of32KGNDfly5P2g3iXY9VJkhdM',
    appId: '1:964464805510:ios:8b0db1f132002a24447307',
    messagingSenderId: '964464805510',
    projectId: 'messaging-app-371aa',
    storageBucket: 'messaging-app-371aa.appspot.com',
    androidClientId: '964464805510-05uatak15i4t5nkiejp610k3be6ramo2.apps.googleusercontent.com',
    iosClientId: '964464805510-svhl2a7c27gj5efc7mbdof15h4uqiclu.apps.googleusercontent.com',
    iosBundleId: 'com.example.messageApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiS8bt7of32KGNDfly5P2g3iXY9VJkhdM',
    appId: '1:964464805510:ios:8b0db1f132002a24447307',
    messagingSenderId: '964464805510',
    projectId: 'messaging-app-371aa',
    storageBucket: 'messaging-app-371aa.appspot.com',
    androidClientId: '964464805510-05uatak15i4t5nkiejp610k3be6ramo2.apps.googleusercontent.com',
    iosClientId: '964464805510-svhl2a7c27gj5efc7mbdof15h4uqiclu.apps.googleusercontent.com',
    iosBundleId: 'com.example.messageApp',
  );
}
